# .github/workflows/gemini-pr.yml

name: Gemini Auto-Coding Task

on:
  # 'gemini-task' ラベルが付与されたときに起動
  issues:
    types: [labeled]
  
  # 手動でActionsタブから実行できるようにする
  workflow_dispatch:

jobs:
  build-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # このステップは、どのトリガーでも実行されます
      - name: Show Event Name
        run: echo "Workflow triggered by: ${{ github.event_name }}"

      # これらのステップは、'issues' イベントで 'gemini-task' ラベルが付与された場合のみ実行されます
      - name: Show Issue Context (Conditional)
        if: github.event_name == 'issues' && github.event.label.name == 'gemini-task'
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body:"
          echo "${{ github.event.issue.body }}"
          echo "Issue Number: ${{ github.event.issue.number }}"

      - name: Call Gemini API (Placeholder)
        if: github.event_name == 'issues' && github.event.label.name == 'gemini-task'
        run: echo "TODO: Implement Gemini API call here."

      - name: Create Pull Request (Placeholder)
        if: github.event_name == 'issues' && github.event.label.name == 'gemini-task'
        run: echo "TODO: Implement PR creation logic here."
